### ISSUE TITLE
Doesn't load match/score data

### ISSUE THREAD

**Issue by hadess** [jonian/kickoff-player#15]
I'm slowly packaging the program as a Flatpak, including all the dependencies, and I got to the point where it shows a window, but it doesn't seem to be able to parse the data it downloads throwing:
```sh
$ kickoff-player 
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/kickoff-player/handlers/match.py", line 66, in initial_setup
    self.update_competitions_data()
  File "/app/lib/kickoff-player/handlers/match.py", line 94, in update_competitions_data
    self.app.scores_api.save_competitions()
  File "/app/lib/kickoff-player/apis/scores.py", line 55, in save_competitions
    'section_name': self.section_name(codes, item['section']),
  File "/app/lib/kickoff-player/apis/scores.py", line 190, in section_name
    name = name[0]['title']
IndexError: list index out of range
```

**Comment by jonian** [comment]
Hi @hadess, the [score api](https://github.com/jonian/kickoff-player/blob/master/apis/scores.py) can be fixed. The problem is with the [streams scraper](https://github.com/jonian/kickoff-player/blob/master/apis/streams.py) that uses livefootballol.me website. That website does not offer any more acestream links. I was planning to replace it with soccerstreams.net but they also stopped to offer acestream links, so this app is not very useful right now.

**Comment by hadess** [comment]
That's a shame. FWIW, I also tried to get it to play other acestream URLs, but wasn't able to get it working either, but that's likely a problem with `acestreamengine` on my setup.

**Comment by jonian** [comment]
I fixed the index out of range errors and the app should start. Playing URLs works fine, try with acestream through docker:

```bash
docker run -p 6878:6878 -p 62062:62062 -it cturra/acestream
```
